package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 2, 2023, 2:41:08 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Candidat generated by hbm2java
 */
@Entity
@Table(name="candidat"
    ,schema="public"
)
public class Candidat  implements java.io.Serializable {


     private int idCandidat;
     private NiveauQualification niveauQualification;
     private String nom;
     private String prenom;
     private Date dateNaissance;
     private String adressePostale;
     private String adresseEmail;
     private String cv;
     private Date dateDepot;
     private Set<SecteurActivite> secteurActivites = new HashSet<SecteurActivite>(0);
     private Set<MessageOffreemploi> messageOffreemplois = new HashSet<MessageOffreemploi>(0);
     private Set<MessageCandidat> messageCandidats = new HashSet<MessageCandidat>(0);

    public Candidat() {
    }

	
    public Candidat(int idCandidat) {
        this.idCandidat = idCandidat;
    }
    public Candidat(int idCandidat, NiveauQualification niveauQualification, String nom, String prenom, Date dateNaissance, String adressePostale, String adresseEmail, String cv, Date dateDepot, Set<SecteurActivite> secteurActivites, Set<MessageOffreemploi> messageOffreemplois, Set<MessageCandidat> messageCandidats) {
       this.idCandidat = idCandidat;
       this.niveauQualification = niveauQualification;
       this.nom = nom;
       this.prenom = prenom;
       this.dateNaissance = dateNaissance;
       this.adressePostale = adressePostale;
       this.adresseEmail = adresseEmail;
       this.cv = cv;
       this.dateDepot = dateDepot;
       this.secteurActivites = secteurActivites;
       this.messageOffreemplois = messageOffreemplois;
       this.messageCandidats = messageCandidats;
    }

    public Candidat(String nom, String prenom, String mail, String adressePostale, String cv, Date datedepot, Date datenaissance,
                    NiveauQualification byId, Set<SecteurActivite> liste_secteurs) {
        this.nom = nom;
        this.prenom = prenom;
        this.adresseEmail = mail;
        this.adressePostale = adressePostale;
        this.cv = cv;
        this.dateNaissance = datenaissance;
        this.dateDepot = datedepot;
        this.niveauQualification = byId;
        this.secteurActivites = liste_secteurs;
    }
//@Column(name="id_candidat", unique=true, nullable=false)
    @Id
     @SequenceGenerator(name="CANDIDAT_ID_GENERATOR", sequenceName="CANDIDAT_ID_SEQ", allocationSize=1)
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="CANDIDAT_ID_GENERATOR")
    public int getIdCandidat() {
        return this.idCandidat;
    }
    
    public void setIdCandidat(int idCandidat) {
        this.idCandidat = idCandidat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="no_qualification")
    public NiveauQualification getNiveauQualification() {
        return this.niveauQualification;
    }
    
    public void setNiveauQualification(NiveauQualification niveauQualification) {
        this.niveauQualification = niveauQualification;
    }

    
    @Column(name="nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom")
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_naissance", length=13)
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    
    @Column(name="adresse_postale")
    public String getAdressePostale() {
        return this.adressePostale;
    }
    
    public void setAdressePostale(String adressePostale) {
        this.adressePostale = adressePostale;
    }

    
    @Column(name="adresse_email")
    public String getAdresseEmail() {
        return this.adresseEmail;
    }
    
    public void setAdresseEmail(String adresseEmail) {
        this.adresseEmail = adresseEmail;
    }

    
    @Column(name="cv")
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_depot", length=13)
    public Date getDateDepot() {
        return this.dateDepot;
    }
    
    public void setDateDepot(Date dateDepot) {
        this.dateDepot = dateDepot;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="secteur_candidat", schema="public", joinColumns = { 
        @JoinColumn(name="no_candidat", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="no_secteur", nullable=false, updatable=false) })
    public Set<SecteurActivite> getSecteurActivites() {
        return this.secteurActivites;
    }
    
    public void setSecteurActivites(Set<SecteurActivite> secteurActivites) {
        this.secteurActivites = secteurActivites;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="candidat")
    public Set<MessageOffreemploi> getMessageOffreemplois() {
        return this.messageOffreemplois;
    }
    
    public void setMessageOffreemplois(Set<MessageOffreemploi> messageOffreemplois) {
        this.messageOffreemplois = messageOffreemplois;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="candidat")
    public Set<MessageCandidat> getMessageCandidats() {
        return this.messageCandidats;
    }
    
    public void setMessageCandidats(Set<MessageCandidat> messageCandidats) {
        this.messageCandidats = messageCandidats;
    }



    public String toStringShort(){
        return "Candidat[idCandidat="+this.idCandidat+", Nom="+this.nom+", Prenom="+this.prenom+"]";
    }


}


