package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 2, 2023, 2:41:08 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import jakarta.persistence.*;

/**
 * MessageOffreemploi generated by hbm2java
 */
@Entity
@Table(name="message_offreemploi"
    ,schema="public"
)
public class MessageOffreemploi  implements java.io.Serializable {


     private int idMessageOffre;
     private Candidat candidat;
     private OffreEmploi offreEmploi;
     private Date dateEnvoi;
     private String corpsMessage;

    public MessageOffreemploi() {
    }

	
    public MessageOffreemploi(int idMessageOffre) {
        this.idMessageOffre = idMessageOffre;
    }
    public MessageOffreemploi(int idMessageOffre, Candidat candidat, OffreEmploi offreEmploi, Date dateEnvoi, String corpsMessage) {
       this.idMessageOffre = idMessageOffre;
       this.candidat = candidat;
       this.offreEmploi = offreEmploi;
       this.dateEnvoi = dateEnvoi;
       this.corpsMessage = corpsMessage;
    }

    public MessageOffreemploi(Candidat byId, OffreEmploi byId1, String corpsMessage, Date dateenvoi) {
        this.candidat=byId;
        this.offreEmploi = byId1;
        this.corpsMessage = corpsMessage;
        this.dateEnvoi = dateenvoi;
    }

    @Id
    @Column(name="id_message_offre", unique=true, nullable=false)
     @SequenceGenerator(name="MESSAGE_OFFRE_ID_GENERATOR", sequenceName="MESSAGE_OFFRE_ID_SEQ", allocationSize=1)
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MESSAGE_OFFRE_ID_GENERATOR")
    public int getIdMessageOffre() {
        return this.idMessageOffre;
    }
    
    public void setIdMessageOffre(int idMessageOffre) {
        this.idMessageOffre = idMessageOffre;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="no_candidat")
    public Candidat getCandidat() {
        return this.candidat;
    }
    
    public void setCandidat(Candidat candidat) {
        this.candidat = candidat;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="no_offre")
    public OffreEmploi getOffreEmploi() {
        return this.offreEmploi;
    }
    
    public void setOffreEmploi(OffreEmploi offreEmploi) {
        this.offreEmploi = offreEmploi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_envoi", length=13)
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    
    @Column(name="corps_message")
    public String getCorpsMessage() {
        return this.corpsMessage;
    }
    
    public void setCorpsMessage(String corpsMessage) {
        this.corpsMessage = corpsMessage;
    }




}


