package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 2, 2023, 2:41:08 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import java.util.List;

import jakarta.persistence.*;

/**
 * MessageCandidat generated by hbm2java
 */
@Entity
@Table(name="message_candidat"
    ,schema="public"
)
public class MessageCandidat  implements java.io.Serializable {


     private int idMessageCandidat;
     private Candidat candidat;
     private OffreEmploi offreEmploi;
     private Date dateEnvoi;
     private String corpsMessage;

    public MessageCandidat() {
    }

	
    public MessageCandidat(int idMessageCandidat) {
        this.idMessageCandidat = idMessageCandidat;
    }
    public MessageCandidat(int idMessageCandidat, Candidat candidat, OffreEmploi offreEmploi, Date dateEnvoi, String corpsMessage) {
       this.idMessageCandidat = idMessageCandidat;
       this.candidat = candidat;
       this.offreEmploi = offreEmploi;
       this.dateEnvoi = dateEnvoi;
       this.corpsMessage = corpsMessage;
    }

    public MessageCandidat(Candidat byId, OffreEmploi byId1, String corpsMessage, Date dateEnvoi) {
        this.candidat = byId;
        this.offreEmploi = byId1;
        this.corpsMessage = corpsMessage;
        this.dateEnvoi = dateEnvoi;
    }

    @Id
    @Column(name="id_message_candidat", unique=true, nullable=false)
     @SequenceGenerator(name="MESSAGE_CANDIDAT_ID_GENERATOR", sequenceName="MESSAGE_CANDIDAT_ID_SEQ", allocationSize=1)
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MESSAGE_CANDIDAT_ID_GENERATOR")
    public int getIdMessageCandidat() {
        return this.idMessageCandidat;
    }
    
    public void setIdMessageCandidat(int idMessageCandidat) {
        this.idMessageCandidat = idMessageCandidat;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="no_candidat")
    public Candidat getCandidat() {
        return this.candidat;
    }
    
    public void setCandidat(Candidat candidat) {
        this.candidat = candidat;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="no_offre")
    public OffreEmploi getOffreEmploi() {
        return this.offreEmploi;
    }
    
    public void setOffreEmploi(OffreEmploi offreEmploi) {
        this.offreEmploi = offreEmploi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_envoi", length=13)
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    
    @Column(name="corps_message")
    public String getCorpsMessage() {
        return this.corpsMessage;
    }
    
    public void setCorpsMessage(String corpsMessage) {
        this.corpsMessage = corpsMessage;
    }






}


